stages:
  - triggers

Run_Alpha:
  stage: triggers
  trigger:
    include: config/cicd-a/.gitlab-ci.yml
  rules:
    - if: '$CI_COMMIT_BRANCH == "alpha"'

Run_Beta:
  stage: triggers
  trigger:
    include: config/cicd-b/.gitlab-ci.yml
  rules:
    - if: '$CI_COMMIT_BRANCH == "beta"'

Run_Test:
  stage: triggers
  trigger:
    include: config/cicd-t/.gitlab-ci.yml
  rules:
    - if: '$CI_COMMIT_BRANCH == "test"'

Run_Demo:
  stage: triggers
  trigger:
    include: config/cicd-d/.gitlab-ci.yml
  rules:
    - if: '$CI_COMMIT_BRANCH == "demo"'

Run_Prod:
  stage: triggers
  trigger:
    include: config/cicd-p/.gitlab-ci.yml
  rules:
    - if: '$CI_COMMIT_BRANCH == "prod"'

