export const GET_CHANNELS = "GET_CHANNELS";
export const GET_CHANNELS_SUCCESS = "GET_CHANNELS_SUCCESS";
export const GET_CHANNELS_FAIL = "GET_CHANNELS_FAIL";
export const GET_CHANNEL_BYID = "GET_CHANNEL_BYID";

export const INSERT_CHANNEL = "INSERT_CHANNEL";
export const INSERT_CHANNEL_SUCCESS = "INSERT_CHANNEL_SUCCESS";
export const INSERT_CHANNEL_FAIL = "INSERT_CHANNEL_FAIL";

export const UPSERT_CHANNEL = "UPSERT_CHANNEL";
export const UPSERT_CHANNEL_SUCCESS = "UPSERT_CHANNEL_SUCCESS";
export const UPSERT_CHANNEL_FAIL = "UPSERT_CHANNEL_FAIL";

export const UPDATE_CHANNEL = "UPDATE_CHANNEL";
export const UPDATE_CHANNEL_SUCCESS = "UPDATE_CHANNEL_SUCCESS";
export const UPDATE_CHANNEL_FAIL = "UPDATE_CHANNEL_FAIL";
export const UPDATE_CHANNEL_AUCTION = "UPDATE_CHANNEL_AUCTION";
export const UPDATE_CHANNEL_AUCTION_END = "UPDATE_CHANNEL_AUCTION_END";
export const UPDATE_CHANNEL_AUCTION_END_SUCCESS = "UPDATE_CHANNEL_AUCTION_END_SUCCESS";
export const UPDATE_CHANNEL_AUCTION_SUCCESS = "UPDATE_CHANNEL_AUCTION_SUCCESS";

export const DELETE_CHANNEL = "DELETE_CHANNEL";
export const DELETE_CHANNEL_SUCCESS = "DELETE_CHANNEL_SUCCESS";
export const DELETE_CHANNEL_FAIL = "DELETE_CHANNEL_FAIL";


export const RESET_CHANNEL_FLAG = "RESET_CHANNEL_FLAG";