// <auto-generated />
using Coreapi.Infrastructure.Notification;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Coreapi.Infrastructure.Migrations.NotificationDb
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20250209115514_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Coreapi.Infrastructure.Notification.UserConnection", b =>
                {
                    b.Property<string>("SearchUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.HasKey("SearchUserId");

                    b.ToTable("UserConnections");
                });
#pragma warning restore 612, 618
        }
    }
}
