// <auto-generated />
using Coreapi.Infrastructure.Notification;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Coreapi.Infrastructure.Migrations.NotificationDb
{
    [DbContext(typeof(NotificationDbContext))]
    partial class NotificationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Coreapi.Infrastructure.Notification.UserConnection", b =>
                {
                    b.Property<string>("SearchUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.HasKey("SearchUserId");

                    b.ToTable("UserConnections");
                });

            modelBuilder.Entity("Coreapi.Infrastructure.Notification.UserToken", b =>
                {
                    b.Property<string>("SearchUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.Property<int>("Platform")
                        .HasColumnType("INTEGER");

                    b.HasKey("SearchUserId", "Token");

                    b.ToTable("UserTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
