
export const GET_ELECTPROJECTS = "GET_ELECTPROJECT"
export const GET_ELECTPROJECTS_SUCCESS = "GET_ELECTPROJECT_SUCCESS"
export const GET_ELECTPROJECTS_FAIL = "GET_ELECTPROJECT_FAIL"

export const GET_ELECTPROJECTS_FILTER = "GET_ELECTPROJECTS_FILTER"
export const GET_ELECTPROJECTS_FILTER_SUCCESS = "GET_ELECTPROJECTS_FILTER_SUCCESS"
export const GET_ELECTPROJECTS_FILTER_FAIL = "GET_ELECTPROJECTS_FILTER_FAIL"

export const GET_ELECTPROJECTS_FULL_FILTER = "GET_ELECTPROJECTS_FULL_FILTER"
export const GET_ELECTPROJECTS_FULL_FILTER_SUCCESS = "GET_ELECTPROJECTS_FULL_FILTER_SUCCESS"
export const GET_ELECTPROJECTS_FULL_FILTER_CHILDREN_SUCCESS = "GET_ELECTPROJECTS_FULL_FILTER_CHILDREN_SUCCESS"
export const GET_ELECTPROJECTS_FULL_FILTER_FAIL = "GET_ELECTPROJECTS_FULL_FILTER_FAIL"

export const GET_ELECTPROJECTS_ENG = "GET_ELECTPROJECTS_ENG"
export const GET_ELECTPROJECTS_ENG_SUCCESS = "GET_ELECTPROJECTS_ENG_SUCCESS"
export const GET_ELECTPROJECTS_ENG_FAIL = "GET_ELECTPROJECTS_ENG_FAIL"

export const GET_ELECTPROJECT_REPORT = "GET_ELECTPROJECT_REPORT"
export const GET_ELECTPROJECT_REPORT_SUCCESS = "GET_ELECTPROJECT_REPORT_SUCCESS"
export const GET_ELECTPROJECT_REPORT_FAIL = "GET_ELECTPROJECT_REPORT_FAIL"

export const GET_ELECTPROJECT_FILES = "GET_ELECTPROJECT_FILES"
export const GET_ELECTPROJECT_FILES_SUCCESS = "GET_ELECTPROJECT_FILES_SUCCESS"
export const GET_ELECTPROJECT_FILES_FAIL = "GET_ELECTPROJECT_FILES_FAIL"

export const GET_ELECTPROJECT_FREE = "GET_ELECTPROJECT_FREE"
export const GET_ELECTPROJECT_FREE_SUCCESS = "GET_ELECTPROJECT_FREE_SUCCESS"
export const GET_ELECTPROJECT_FREE_FAIL = "GET_ELECTPROJECT_FREE_FAIL"

export const GET_PANEL_MAKER = "GET_PANEL_MAKER"
export const GET_PANEL_MAKER_SUCCESS = "GET_PANEL_MAKER_SUCCESS"
export const GET_PANEL_MAKER_FAIL = "GET_PANEL_MAKER_FAIL"

export const INSERT_ELECTPROJECT = "INSERT_ELECTPROJECT"
export const INSERT_ELECTPROJECT_SUCCESS = "INSERT_ELECTPROJECT_SUCCESS"
export const INSERT_ELECTPROJECT_FAIL = "INSERT_ELECTPROJECT_FAIL"

export const UPSERT_ElECTROJECT = "UPSERT_ElECTROJECT"
export const UPSERT_ElECTROJECT_SUCCESS = "UPSERT_ElECTROJECT_SUCCESS"
export const UPSERT_ElECTROJECT_FAIL = "UPSERT_ElECTROJECT_FAIL"

export const UPDATE_ELECTPROJECT = "UPDATE_ELECTPROJECT"
export const UPDATE_ELECTPROJECT_SUCCESS = "UPDATE_ELECTPROJECT_SUCCESS"
export const UPDATE_ELECTPROJECT_FAIL = "UPDATE_ELECTPROJECT_FAIL"

export const UPDATE_ELECTPROJECT_ENG = "UPDATE_ELECTPROJECT_ENG"
export const UPDATE_ELECTPROJECT_ENG_NEW = "UPDATE_ELECTPROJECT_ENG_NEW"


export const DELETE_ELECTPROJECT = "DELETE_ELECTPROJECT"
export const DELETE_ELECTPROJECT_SUCCESS = "DELETE_ELECTPROJECT_SUCCESS"
export const DELETE_ELECTPROJECT_FAIL = "DELETE_ELECTPROJECT_FAIL"

export const UPDATE_ELECTPROJECT_DETAILS = "UPDATE_ELECTPROJECT_DETAILS"
export const UPDATE_ELECTPROJECT_DETAILS_SUCCESS = "UPDATE_ELECTPROJECT_DETAILS_SUCCESS"
export const UPDATE_ELECTPROJECT_DETAILS_FAIL = "UPDATE_ELECTPROJECT_DETAILS_FAIL"

export const UPDATE_ELECTPROJECT_DETAILS_NEW = "UPDATE_ELECTPROJECT_DETAILS_NEW"
export const UPDATE_ELECTPROJECT_DETAILS_NEW_SUCCESS = "UPDATE_ELECTPROJECT_DETAILS_NEW_SUCCESS"
export const UPDATE_ELECTPROJECT_DETAILS_NEW_FAIL = "UPDATE_ELECTPROJECT_DETAILS_NEW_FAIL"

export const ADD_FILE_ELECTPROJECT = "ADD_FILE_ELECTPROJECT"
export const ADD_FILE_ELECTPROJECT_SINGLE = "ADD_FILE_ELECTPROJECT_SINGLE"
export const ADD_FILE_ELECTPROJECT_SUCCESS = "ADD_FILE_ELECTPROJECT_SUCCESS"
export const ADD_FILE_ELECTPROJECT_FAIL = "ADD_FILE_ELECTPROJECT_FAIL"

export const UPDATE_PROCESS_EXPERT_STAGE = "UPDATE_PROCESS_EXPERT_STAGE"
export const UPDATE_PROCESS_MAP_STAGE = "UPDATE_PROCESS_MAP_STAGE"
export const UPDATE_PROCESS_DEFECT_STAGE = "UPDATE_PROCESS_DEFECT_STAGE"
export const UPDATE_PROCESS_STAGE_SUCCESS = "UPDATE_PROCESS_STAGE_SUCCESS"
export const UPDATE_PROCESS_STAGE_FAIL = "UPDATE_PROCESS_STAGE_FAIL"

export const UPDATE_PROCESS_EXPERT_STAGE_NEW = "UPDATE_PROCESS_EXPERT_STAGE_NEW"
export const UPDATE_PROCESS_MAP_STAGE_NEW = "UPDATE_PROCESS_MAP_STAGE_NEW"
export const UPDATE_PROCESS_DEFECT_STAGE_NEW = "UPDATE_PROCESS_DEFECT_STAGE_NEW"
export const UPDATE_PROCESS_STAGE_NEW_SUCCESS = "UPDATE_PROCESS_STAGE_NEW_SUCCESS"
export const UPDATE_PROCESS_STAGE_NEW_FAIL = "UPDATE_PROCESS_STAGE_NEW_FAIL"

export const SEND_ELECTPROJECT_TOELECT = "SEND_ELECTPROJECT_TOELECT"
export const SEND_ELECTPROJECT_TOELECT_SUCCESS = "SEND_ELECTPROJECT_TOELECT_SUCCESS"
export const SEND_ELECTPROJECT_TOELECT_FAIL = "SEND_ELECTPROJECT_TOELECT_FAIL"

export const SUBMIT_ELECTPROJECT_ADMIN = "SUBMIT_ELECTPROJECT_ADMIN"
export const SUBMIT_ELECTPROJECT_ADMIN_SUCCESS = "SUBMIT_ELECTPROJECT_ADMIN_SUCCESS"
export const SUBMIT_ELECTPROJECT_ADMIN_FAIL = "SUBMIT_ELECTPROJECT_ADMIN_FAIL"

export const ADD_PANEL_MAKER = "ADD_PANEL_MAKER"
export const ADD_PANEL_MAKER_SUCCESS = "ADD_PANEL_MAKER_SUCCESS"
export const ADD_PANEL_MAKER_FAIL = "ADD_PANEL_MAKER_FAIL"

export const SUBMIT_PACKAGE = "SUBMIT_PACKAGE"
export const SUBMIT_PACKAGE_SUCCESS = "SUBMIT_PACKAGE_SUCCESS"
export const SUBMIT_PACKAGE_FAIL = "SUBMIT_PACKAGE_FAIL"

export const RESET_PACKAGE = "RESET_PACKAGE"
export const RESET_PACKAGE_SUCCESS = "RESET_PACKAGE_SUCCESS"
export const RESET_PACKAGE_FAIL = "RESET_PACKAGE_FAIL"

export const STOP_ELECTPROJECT = "STOP_ELECTPROJECT"
export const STOP_ELECTPROJECT_SUCCESS = "STOP_ELECTPROJECT_SUCCESS"
export const STOP_ELECTPROJECT_FAIL = "STOP_ELECTPROJECT_FAIL"

export const SUBMIT_PANEL = "SUBMIT_PANEL"
export const SUBMIT_PANEL_SUCCESS = "SUBMIT_PANEL_SUCCESS"
export const SUBMIT_PANEL_FAIL = "SUBMIT_PANEL_FAIL"

export const RESOLVED_DEFECT = "RESOLVED_DEFECT"
export const RESOLVED_DEFECT_SUCCESS = "RESOLVED_DEFECT_SUCCESS"
export const RESOLVED_DEFECT_FAIL = "RESOLVED_DEFECT_FAIL"

export const AMOUNT_SMS = "AMOUNT_SMS"
export const AMOUNT_SMS_SUCCESS = "AMOUNT_SMS_SUCCESS"
export const AMOUNT_SMS_FAIL = "AMOUNT_SMS_FAIL"

export const UPDATE_ELECTPROJECT_STATUS = "UPDATE_ELECTPROJECT_STATUS"
export const UPDATE_ELECTPROJECT_STATUS_SUCCESS = "UPDATE_ELECTPROJECT_STATUS_SUCCESS"
export const UPDATE_ELECTPROJECT_STATUS_FAIL = "UPDATE_ELECTPROJECT_STATUS_FAIL"


export const UPDATE_ELECTPROJECT_DEFECT_DES = "UPDATE_ELECTPROJECT_DEFECT_DES"
export const UPDATE_ELECTPROJECT_DEFECT_DES_SUCCESS = "UPDATE_ELECTPROJECT_DEFECT_DES_SUCCESS"
export const UPDATE_ELECTPROJECT_DEFECT_DES_FAIL = "UPDATE_ELECTPROJECT_DEFECT_DES_FAIL"


export const UPSERT_CHECKLIST_EDC = "UPSERT_CHECKLIST_EDC"
export const UPSERT_CHECKLIST_EDC_SUCCESS = "UPSERT_CHECKLIST_EDC_SUCCESS"
export const UPSERT_CHECKLIST_EDC_FAIL = "UPSERT_CHECKLIST_EDC_FAIL"

export const UPDATE_BY_EDC = "UPDATE_BY_EDC"
export const UPDATE_BY_EDC_SUCCESS = "UPDATE_BY_EDC_SUCCESS"
export const UPDATE_BY_EDC_FAIL = "UPDATE_BY_EDC_FAIL"

export const GET_PROJECT_INFO = "GET_PROJECT_INFO"
export const GET_PROJECT_INFO_SUCCESS = "GET_PROJECT_INFO_SUCCESS"
export const GET_PROJECT_INFO_FAIL = "GET_PROJECT_INFO_FAIL"

export const RESET_ELECTPROJECT_FLAG = "RESET_ELECTPROJECT_FLAG"