export const GET_LIST_QUARTERTARIFF = "GET_LIST_QUARTERTARIFF"
export const GET_LIST_QUARTERTARIFF_SUCCESS = "GET_LIST_QUARTERTARIFF_SUCCESS"
export const GET_LIST_QUARTERTARIFF_FAIL = "GET_LIST_QUARTERTARIFF_FAIL"