export const GET_PAYMENT_MELLI = "GET_PAYMENT_MELLI"
export const GET_PAYMENT_MELLI_PUBLIC = "GET_PAYMENT_MELLI_PUBLIC"
export const GET_PAYMENT_MELLI_SUCCESS = "GET_PAYMENT_MELLI_SUCCESS"
export const GET_PAYMENT_MELLI_FAIL = "GET_PAYMENT_MELLI_FAIL"



export const PAYMENT_MELLI_RESET = "PAYMENT_MELLI_RESET"