// Endpoint constants. Port the full set (~81) from old-ui/src/helpers/url_helper.js
// one domain at a time (see /migrate-feature). Paths are relative to VITE_API_URL,
// exactly as in old-ui (the base URL already includes any /api/v1.0 segment).
export const endpoints = {
  auth: {
    login: '/Identity/Login',
    loginByCode: '/Identity/LoginByCode',
    logout: '/Identity/Logout',
    changePassword: '/Identity/ChangePassword',
  },
  engineers: {
    list: 'Engineers/GetEngineerByClient',
    upsert: 'Engineers/UpsertEngineer',
    upsertHistory: 'Engineers/UpsertEngHistory',
  },
  users: {
    files: '/Users/GetUserFiles',
    addFile: '/Users/AddFile',
    deleteFile: '/Users/DeleteFile',
    info: '/Users/GetUserInfo',
  },
  electProjects: {
    fullFilter: '/ElectProjects/GetClientElectProjectsFullFilter',
    upsert: '/ElectProjects/Upsert',
    files: '/ElectProjects/GetElectProjectFilesById',
    addFile: '/ElectProjects/AddFile',
    update: '/ElectProjects/UpdateElectProject',
    updateByEng: '/ElectProjects/UpdateElectProjectByEng',
    delete: '/ElectProjects/DeleteElectProject',
    submitByAdmin: '/ElectProjects/SubmitByAdmin',
    amountSms: '/ElectProjects/AmountSms',
    panelMakers: '/ElectProjects/GetPanelMaker',
    addPanelMaker: '/ElectProjects/AddPanelMaker',
    stop: '/ElectProjects/StopElectProject',
    submitPanel: '/ElectProjects/SubmitPanel',
  },
  support: {
    list: 'Supports/GetSupports',
    upsert: 'Supports/Upsert',
    closed: 'Supports/ClosedSupport',
    tickets: 'Supports/GetTickets',
    upsertTicket: 'Supports/UpsertTicket',
    usersForSupport: '/Users/GetUsersForSupport',
    addFile: 'Supports/AddFile',
    files: 'Supports/GetSupportFiles',
    deleteFile: '/Supports/DeleteFile',
  },
  accounting: {
    transactions: '/Transactions/GetClientUserTransactions',
    invoices: '/Transactions/GetClientInvoices',
    engInvoices: '/Transactions/GetEngClientInvoices',
    paymentCustom: '/Transactions/PaymentCustom',
    engPaymentCustom: '/Transactions/EngPaymentCustom',
  },
  engWork: {
    list: '/Transactions/GetClientEngWork',
    quarterTariffs: 'QuarterTariffs/GetQuarterTariffs',
    quotaBurnList: 'Quotas/GetEngQuotaBurnList',
    quotaBurnApprove: 'Quotas/EngQuotaBurnApproved',
    quotaBurnUpdate: 'Quotas/EngQuotaBurnUpdate',
  },
  reports: {
    electProjectReport: '/ElectProjects/GetClientElectProjectReport',
    engInvoiceReport: '/Transactions/GetClientEngInvoiceReport',
  },
  engPayment: {
    tasks: 'Transactions/GetEngPaymentTasks',
    list: 'Transactions/GetEngPaymentList',
    upsert: 'Transactions/UpsertEngPaymentList',
    update: 'Transactions/UpdateEngPaymentList',
    approve: 'Transactions/EngPaymentApproved',
  },
  metabase: {
    dashboardToken: 'MetaBase/GetDashboardToken',
  },
  public: {
    projectInfo: '/ElectProjects/GetProjectInfo',
    paymentMelliPublic: '/Identity/PaymentMelliPublic',
  },
  // Landing site content — served anonymous (no auth), global (no client).
  landing: {
    announcementsAll: '/Announcements/GetAll',
    announcementsLatest: '/Announcements/GetLatest',
    announcementsUrgent: '/Announcements/GetUrgent',
    announcementBySlug: '/Announcements/GetBySlug',
    meetingsAll: '/Meetings/GetAll',
    meetingsLatest: '/Meetings/GetLatest',
    meetingById: '/Meetings/GetById',
    documentsAll: '/Documents/GetAll',
    documentCategories: '/Documents/GetCategories',
    documentIncrementDownload: '/Documents/IncrementDownload',
    statsAll: '/Stats/GetAll',
    contactSend: '/Contact/Send',
  },
  clients: {
    list: '/Clients/GetAllUsers',
    add: '/Clients/AddUser',
    update: '/clients/UpdateUser',
    delete: '/clients/DeleteUser',
  },
  electProjectProcess: {
    listEng: '/ElectProjectProcesses/GetListProjectProcessEng',
    projectProcess: '/ElectProjectProcesses/ProjectProcess',
    delEpp: '/ElectProjectProcesses/DeleteProjectProcess',
    eppEngChange: '/ElectProjectProcesses/EppEngChange',
    eppUpdateIsMain: '/ElectProjectProcesses/EppUpdateIsMain',
    eppAccepted: '/ElectProjectProcesses/EppAccepted',
    eppApproved: '/ElectProjectProcesses/EppApproved',
    updateByEdc: '/ElectProjects/UpdateByEdc',
    upsertComment: '/ElectProjects/UpsertComment',
    upsertCheckList: '/ElectProjects/UpsertCheckList',
    upsertCheckListEdc: '/ElectProjects/UpsertCheckListEdc',
    upsertErtForm: '/ElectProjects/UpsertErtForm',
  },
} as const
