export const GET_EPP_BYGPID = "GET_EPP_BYGPID"
export const GET_EPP_BYGPID_SUCCESS = "GET_EPP_BYGPID_SUCCESS"
export const GET_EPP_BYGPID_FAIL = "GET_EPP_BYGPID_FAIL"

export const PROJECT_PROCESS = "PROJECT_PROCESS"
export const PROJECT_PROCESS_SUCCESS = "PROJECT_PROCESS_SUCCESS"
export const PROJECT_PROCESS_FAIL = "PROJECT_PROCESS_FAIL"

export const DEL_PROJECT_PROCESS = "DEL_PROJECT_PROCESS"
export const DEL_PROJECT_PROCESS_SUCCESS = "DEL_PROJECT_PROCESS_SUCCESS"
export const DEL_PROJECT_PROCESS_FAIL = "DEL_PROJECT_PROCESS_FAIL"

export const GET_LIST_PROJECT_PROCESS_ENG = "GET_LIST_PROJECT_PROCESS_ENG"
export const GET_LIST_PROJECT_PROCESS_REPORT = "GET_LIST_PROJECT_PROCESS_REPORT"
export const GET_LIST_PROJECT_PROCESS_ENG_SUCCESS = "GET_LIST_PROJECT_PROCESS_ENG_SUCCESS"
export const GET_LIST_PROJECT_PROCESS_ENG_FAIL = "GET_LIST_PROJECT_PROCESS_ENG_FAIL"

export const SELECT_GP = "SELECT_GP"
export const DESELECT_GP = "DESELECT_GP"

export const UPSERT_COMMENT = "UPSERT_COMMENT"
export const UPSERT_COMMENT_SUCCESS = "UPSERT_COMMENT_SUCCESS"
export const UPSERT_COMMENT_FAIL = "UPSERT_COMMENT_FAIL"


export const UPSERT_CHECKLIST = "UPSERT_CHECKLIST"
export const UPSERT_CHECKLIST_SUCCESS = "UPSERT_CHECKLIST_SUCCESS"
export const UPSERT_CHECKLIST_FAIL = "UPSERT_CHECKLIST_FAIL"


export const UPSERT_ERTFORM = "UPSERT_ERTFORM"
export const UPSERT_ERTFORM_SUCCESS = "UPSERT_ERTFORM_SUCCESS"
export const UPSERT_ERTFORM_FAIL = "UPSERT_ERTFORM_FAIL"

export const EPP_APPROVED = "EPP_APPROVED"
export const EPP_APPROVED_SUCCESS = "EPP_APPROVED_SUCCESS"
export const EPP_APPROVED_FAIL = "EPP_APPROVED_FAIL"


export const EPP_ACCEPTED = "EPP_ACCEPTED"
export const EPP_ACCEPTED_SUCCESS = "EPP_ACCEPTED_SUCCESS"
export const EPP_ACCEPTED_FAIL = "EPP_ACCEPTED_FAIL"


export const EPP_UPDATE_IS_MAIN = "EPP_UPDATE_IS_MAIN"
export const EPP_UPDATE_IS_MAIN_SUCCESS = "EPP_UPDATE_IS_MAIN_SUCCESS"
export const EPP_UPDATE_IS_MAIN_FAIL = "EPP_UPDATE_IS_MAIN_FAIL"


export const RESET_ELECT_PROCESS_FLAG = "RESET_ELECT_PROCESS_FLAG"