export const REQUEST_DEMO = "REQUEST_DEMO"
export const REQUEST_DEMO_SUCCESS = "REQUEST_DEMO_SUCCESS"
export const REQUEST_DEMO_FAIL = "REQUEST_DEMO_FAIL"

export const RESET_REQUEST_DEMO = "RESET_REQUEST_DEMO"
